### ISSUE TITLE
测试发现此源码缺少2个重要的功能类型源文件

### ISSUE THREAD

**Issue by hgjnet** [learnstartup/4tweb#1]
如下：
1、/index.php?m=app&c=shopadvantage&a=shopmanageadd&app=4tshop 打开这个路径应该是触发的是此路径文件
\data\compile\template\4tshop\default\extensions\4tshop\template\shopadvantage_shopmanageadd.tpl
2、/index.php?m=app&c=myaccount&page=1&app=4tschool&a=run&schoolid=11045打开这个路径应该触发的是此路径文件\src\extensions/4tschool/template/links.htm
目前发现这2个文件并不存在，希望尽快修改上传！

**Comment by 81552433qqcom** [comment]
你好, 请能指明是从哪个链接进去的吗，我们本地不能重现此问题

**Comment by 81552433qqcom** [comment]
2个月没有反馈，我们这边不能重现，当成已解决。
