### ISSUE TITLE
前端页面的问题

### ISSUE THREAD

**Issue by hitrust** [learnstartup/4tweb#2]
1.个人中心，
![1111](https://cloud.githubusercontent.com/assets/3360631/3839713/a706b69c-1e14-11e4-92cd-9bb2fb5e4716.JPG)

![2222](https://cloud.githubusercontent.com/assets/3360631/3839771/324362f0-1e15-11e4-92b7-ef68daf42149.JPG)

2.个人用户注册后，怎么申请成为商户？

**Comment by 81552433qqcom** [comment]
对于1已经解决.

对于2, 用户成为商户，首先设置为商户账号:
外卖平台设置 -> 一级区域设置 -> 商家账号设置

然后在商家列表编辑某个商家 指定商家账号
