### ISSUE TITLE
web后台页面的管理问题

### ISSUE THREAD

**Issue by hitrust** [learnstartup/4tweb#3]
1.一级区域设置，怎么添加和删除
2.外卖标签管理，没有分页和删除
3.分类结构管理看的不是很明白呀
4.商家管理没有删除功能，

**Comment by 81552433qqcom** [comment]
1. 请在pw_4t_school_opened里面设置
2. 外卖标签管理可以代理账号在前台改 后台只看
3. 分类结构是树形结构，类似京东左边的分类，但团队觉得对于订餐过于复杂 所以这个没有在前台有显示
4. 商家只有下架功能 没有删除 也请不要删除数据
